server:
  port: 8081
spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/easystudy
      username: root
      password: root1234
  redis:
    port: 6379
    host: 127.0.0.1
    password:
    database: 0
    lettuce:
      pool:
        max-idle: 8
        max-wait: 100ms
        min-idle: 8
        max-active: 8
  main:
    banner-mode: off
mybatis:
  type-aliases-package: com.example.easystudy.util
  mapperLocations: classpath:mappers/*.xml

baseUrl: "http://localhost:8081"

# 以下为阿里云短信服务的配置
accessKeyId:
accessKeySecret:
signName:
templateCode:
